name: backtest-dev-prod

# 개발 환경에서 프로덕션 설정 테스트용
# reload 없이 워커 모드로 실행

services:
  backtest-be-fast:
    build:
      context: ./backtest_be_fast
      dockerfile: Dockerfile
    image: backtest-be-fast:dev-prod
    container_name: backtest-be-fast-dev-prod
    networks:
      - backtest-net
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DEBUG=false
    volumes:
      - ./backtest_be_fast:/app
      - backtest_be_fast_venv:/opt/venv
    # 개발 환경 프로덕션 모드: 8 논리 코어 → 17 workers
    # reload 비활성화 (성능 테스트용)
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "17", "--limit-concurrency", "100", "--backlog", "200", "--timeout-keep-alive", "30"]
    
  backtest-fe:
    build:
      context: ./backtest_fe
      dockerfile: Dockerfile.dev
    image: backtest-fe:dev
    container_name: backtest-fe-dev
    networks:
      - backtest-net
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      backtest-be-fast:
        condition: service_started
    ports:
      - "5173:5173"
    volumes:
      - ./backtest_fe:/app
      - backtest_fe_node_modules:/app/node_modules
    env_file:
      - .env
    environment:
      - "VITE_API_BASE_URL=${VITE_API_BASE_URL:-/api}"
      - "API_PROXY_TARGET=${API_PROXY_TARGET:-http://backtest-be-fast:8000}"
      - "FASTAPI_PROXY_TARGET=${FASTAPI_PROXY_TARGET:-http://backtest-be-fast:8000}"
    command: ["npm", "run", "dev"]

volumes:
  backtest_fe_node_modules:
  backtest_be_fast_venv:

networks:
  backtest-net:
    name: backtest-network
